projects:
  Ubor-uborfinal:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-west-2
        apiId: szn2ch45nvfhfcxmyrzhxgy66e
        maxDepth: 2
extensions:
  amplify:
    version: 3
